# **************************************************************************** #
#                                                                              #
#                                                         :::      ::::::::    #
#    Vagrantfile                                        :+:      :+:    :+:    #
#                                                     +:+ +:+         +:+      #
#    By: shamsate <shamsate@student.1337.ma>        +#+  +:+       +#+         #
#                                                 +#+#+#+#+#+   +#+            #
#    Created: 2026/06/11 15:45:21 by shamsate          #+#    #+#              #
#    Updated: 2026/06/11 15:48:14 by shamsate         ###   ########.fr        #
#                                                                              #
# **************************************************************************** #

Vagrant.configure("2") do |config|
	config.vm.box = "debian/bookworm64"
	config.vm.boot_timeout = 600
	config.ssh.insert_key = false

	config.vm.define "shamsateS" do |server|
		server.vm.hostname = "shamsateS"
		server.vm.network "private_network", ip: "192.168.56.110"

		server.vm.provider "virtualbox" do |vb|
			vb.memory = "2048"
			vb.cpus = 2
		end

		server.vm.provision "shell", path: "scripts/k3s-server.sh"
	end
end
